name: Build and test ijson

# Build on every branch push, tag push, and pull request change:
on:
  push:
  pull_request:
  schedule:
  # 00:00 UTC every Saturday, don't bother anyone
  - cron: '0 0 * * 6'

env:
  UV_EXTRA_INDEX_URL: https://pypi.riseproject.dev/simple/
  UV_INDEX_STRATEGY: unsafe-best-match

jobs:

  fast_tests:
    name: Build ijson and run unit tests (${{ matrix.os }}, ${{ matrix.python_version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, ubuntu-24.04-riscv, windows-2025, macos-14]
        python_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - os: ubuntu-latest
            python_version: "pypy3.10"

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Python ${{ matrix.python_version }}
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          activate-environment: true
          python-version: ${{ matrix.python_version }}

      - name: Install Yajl
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt install libyajl-dev

      - name: Build ijson
        env:
          IJSON_EMBED_YAJL: ${{ matrix.os != 'ubuntu-latest' && '1' || '0' }}
        run: uv pip install .

      - name: Install test dependencies
        run: uv pip install -r test-requirements.txt

      - name: Run unittests
        run: pytest -vv

      - name: Run doctests
        run: pytest --doctest-modules --doctest-ignore-import-errors src
